name: CI

on:
  push:
    branches:
    - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '14.x'
          registry-url: https://registry.npmjs.org
          scope: '@octocat'
 
      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies and run tests
        run: npm install && npm run tsc && npm run lint && npm run test
